services:
  reverse-proxy:
    image: traefik:v3.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/certs:/etc/certs:ro
      - ./traefik:/traefik:ro
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      # tls
      - "--entryPoints.websecure.http.tls=true"
      - "--providers.file.filename=/traefik/traefik.yml"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=api@internal

  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    command:
      - "--config=/glance/glance.yml"
    volumes:
      - ./glance:/glance:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.glance.rule=Host(`glance.localhost`)

  actual:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
    volumes:
      - ./actual/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.rule=Host(`actual.localhost`)

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
          # if you're not running NixOS-WSL you might need this instead
          # - driver: nvidia
          #   count: 1
          #   capabilities: [gpu]
    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama.rule=Host(`ollama.localhost`)

volumes:
  ollama:
